service: workshop-${self:custom.name}

frameworkVersion: '3'

custom:
  name: murat
  export-env:
    overwrite: true
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  # 10k for the whole region is the default, we can limit the whole API gateway here,
  # and also at function level using throttling property
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500

provider:
  name: aws
  # Make our API gateway regional
  endpointType: REGIONAL
  runtime: nodejs18.x
  region: us-east-1 # us-east-1 is the default region for API Gateway if left out
  iam:
    role:
      statements:
        # Creating the Restaurants API: ensure that our lambda functions can access the DynamoDB table
        - Effect: Allow
          Action: dynamodb:scan
          Resource: !GetAtt RestaurantsTable.Arn
          # Securing the API Gateway: Protect the API Gateway endpoint with AWS_IAM: Add a shared IAM permission
          # for now this is shared between the functions, to get-index function the ability to call the `GET /restaurants` endpoint
        - Effect: Allow
          Action: execute-api:Invoke
          Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/${sls:stage}/GET/restaurants
        # Load app configurations from SSM Parameter Store with cache and cache invalidation
        - Effect: Allow
          Action: ssm:GetParameters*
          Resource:
            # Share SSM parameters across these temporary environments
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${param:ssmStage,
              sls:stage}/get-restaurants/config
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${param:ssmStage,
              sls:stage}/search-restaurants/config
  environment:
    baseUrl: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage} # used in Cypress
    rest_api_url: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage} # used in Jest e2e
    deployment: ${sls:stage}
    stage: ${sls:stage}
    serviceName: ${self:service}
    CLOUDFRONT_URL: 'https://d27lew3mfrizo7.cloudfront.net'
    # Fixing the connection closing issue with Middy
    middy_cache_enabled: true
    middy_cache_expiry_milliseconds: 60000 # 1 mins
    # Share SSM parameters across these temporary environments
    # look for a ssmStage parameter from the CLI, and if not found, it'll fall back to the built-in sls:stage variable
    ssmStage: ${param:ssmStage, sls:stage}

plugins:
  # exports the environment variables to a **.env** file.
  - serverless-export-env
  # configures API gateway throttling (10k for the whole region is the default)
  - serverless-api-gateway-throttling

functions:
  get-index:
    handler: functions/get-index.handler
    # When you use the http event in Serverless Framework with AWS as your provider,
    # it automatically creates an Amazon API Gateway for you
    # the properties you set under the http key (like path, method, and cors) define the configuration for this API Gateway.
    events:
      - http:
          path: /
          method: get
          cors: true
    # Exercise: Displaying the restaurants on the landing page
    # Serverless framework ALWAYS uses the logical ID ApiGatewayRestApi for the API Gateway REST API resource it creates.
    # So you can construct the URL for the /restaurants endpoint using the Fn::Sub CloudFormation pseudo function (or the !Sub shorthand)
    # !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}/restaurants
    environment:
      restaurants_api: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}/restaurants
      # Secure API Gateway with User Pools:
      # enable the UI to register and sign in with the Cognito User Pool
      cognito_user_pool_id: !Ref CognitoUserPool
      cognito_client_id: !Ref WebCognitoUserPoolClient
      cognito_server_client_id: !Ref ServerCognitoUserPoolClient
    # Configure custom throttling for the function
    throttling:
      maxRequestsPerSecond: 2000
      maxConcurrentRequests: 1000

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get
          cors: true
          # Securing the API Gateway:
          # Protect the API Gateway endpoint with AWS_IAM: add the authorizer property to the http event
          # anyone who calls the GET /restaurants endpoint would need to sign the HTTP request using their IAM credentials
          authorizer: aws_iam
    # Notice that the restaurants_table environment variable is referencing (using the CloudFormation pseudo function !Ref)
    environment:
      restaurants_table: !Ref RestaurantsTable

  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          cors: true
          # Secure API Gateway with User Pools:
          # After adding this, the POST /restaurants/search endpoint is now an authenticated endpoint.
          # To call it, the user needs to first sign in to the Cognito User Pool we created earlier,
          # obtain an authentication token and include the token in the HTTP request.
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    environment:
      restaurants_table: !Ref RestaurantsTable

# everything under the lower case resources section is custom CloudFormation resources
# that you want to include in the CloudFormation template, all in raw CloudFormation
resources:
  Resources:
    # RestaurantsTable is called the logical Id in CloudFormation,
    # it is a unique id in the CloudFormation template
    # use !Ref or !GetAtt functions to reference a resource
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # DDB has 2 billing modes, PAY_PER_REQUEST (on demand) and provisioned
        BillingMode: PAY_PER_REQUEST
        # DynamoDB operates with HASH and RANGE keys as the schemas you need to specify
        # When you specify an attribute in the key schema
        # you also need to add them to the AttributeDefinitions list so you can specify their type
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH

    # Create a  Cognito User pool
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Allow users to log in with their email addresses.
        AliasAttributes:
          - email
        # Allow usernames to be case insensitive
        UsernameConfiguration:
          CaseSensitive: false
        # Verify that a user owns his/her email address
        # (ie. by sending a verification code to the email)
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireUppercase: true
            RequireSymbols: true
        Schema:
          - AttributeDataType: String
            Mutable: true
            Name: given_name
            Required: true
            StringAttributeConstraints:
              MinLength: '1'
          - AttributeDataType: String
            Mutable: true
            Name: family_name
            Required: true
            StringAttributeConstraints:
              MinLength: '1'
          - AttributeDataType: String
            Mutable: true
            Name: email
            Required: true
            StringAttributeConstraints:
              MinLength: '1'
    # To interact with a Cognito User Pool, you need to create app clients.
    # Each client can be configured with different authentication flows, token expiration,
    # and which attributes it's allowed to read or write.
    # Add Cognito User Pool web client: used by the landing page frontend,
    # this would be used to register new users, and support sign-in and sign-out.
    WebCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: web
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED
    # Add Cognito User Pool server client
    ServerCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: server
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED

  # Since we have added a DynamoDB table to the stack as a custom resource,
  # it's useful to add its name to the stack output.
  # It's not required for the application to work,
  # but it's a good practice to keep important resource information (like DynamoDB table names)
  # in the CloudFormation output so they're easier to find.
  Outputs:
    RestaurantsTableName:
      Value: !Ref RestaurantsTable

    CognitoUserPoolId:
      Value: !Ref CognitoUserPool

    CognitoUserPoolArn:
      Value: !GetAtt CognitoUserPool.Arn

    CognitoUserPoolWebClientId:
      Value: !Ref WebCognitoUserPoolClient

    CognitoUserPoolServerClientId:
      Value: !Ref ServerCognitoUserPoolClient
## !Ref vs !GetAtt
# !Ref refers to the whole resource and gives you a commonly used identification for it (like a resource's name or ID).
# !GetAtt is for when you want to extract a specific attribute from a resource. Usually .Arn
